import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  wrapper: {
    marginVertical: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  title: {
    fontSize: 19,
    fontWeight: '700',
    color: '#1e293b',
  },
  tableContainer: {
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    marginTop: 10,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    alignItems: 'center',
  },
  tableHeader: {
    backgroundColor: '#f8fafc',
  },
  cardContainer: {
    paddingTop: 10,
  },
  cardItem: {
    marginBottom: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    backgroundColor: '#fcfcfc',
  },
  cell: {
    flex: 1,
    paddingHorizontal: 6,
  },
  labelContainer: {
    borderRadius: 18,
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
  },
  labelText: {
    fontSize: 14,
    fontWeight: '600',
  },
  projeto: { flex: 2 },
  categoria: { flex: 2 },
  data: { flex: 2 },
  valor: { flex: 1.5 },
  usuario: { flex: 2 },
  descricao: { flex: 3 },
  comprovante: { flex: 2 },
  aprovacao: { flex: 1.5 },
  aprovacaoToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
  },
  selectContainer: {
    position: 'absolute',
    top: 40,
    right: 0,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 6,
    elevation: 4,
    zIndex: 10,
  },
  selectItem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  selectItemText: {
    fontSize: 14,
  },
  subtitle: {
    fontSize: 14,
    color: '#4b5563',
    marginTop: 2,
  },
  statusButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginBottom: 10,
  },
  statusButton: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
  },
  statusButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
  },
  comprovanteButton: {
    backgroundColor: '#e0e7ff',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comprovanteButtonText: {
    color: '#3730a3',
    fontWeight: '500',
    fontSize: 13,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginTop: 14,
    marginBottom: 6,
    color: '#334155',
  },
  sectionToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 6,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
  },
});
