import { StyleSheet, Dimensions } from "react-native";

export const style = StyleSheet.create({
    menu: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        height: Dimensions.get("window").height,
        backgroundColor: "#FFFFFF",
        position: "relative",
        overflow: "visible",
        zIndex: 1,
    },
    logo: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: 'auto',
        height: 120,
    },
    textoLogo: {
        fontSize: 30,
        fontWeight: "bold",
        color: "#151D48",
    },
    logoContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 20,
      marginBottom: 20,
      gap: 8,
    },
    logoImage: {
      width: 32,
      height: 32,
    },
    botoes: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
        width: 'auto',
    },
    botaoMenu: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        width: 228,
        padding: 24,
        height: 26,
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        gap: 24,
    },
    textoBotaoMenu: {
        fontSize: 16,
        fontWeight: "bold",
        color: "rgb(0, 0, 0)",
    },
    botoesOcultos: {
        flexDirection: "column",
        alignItems: "center",
        gap: 10,
        marginTop: 4,
    },
    botaoIcone: {
        padding: 12,
    },
    navBar:{
        position: 'static',
        top: 0,
        right: 0,
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 100,
        backgroundColor: '#1F48AA',
        width: '100%',
        height: 120,
    },
    tituloNavBar: {
        marginLeft: 30,
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    inputNavbar: {
        backgroundColor: '#FFFFFF',
        paddingVertical: 15,
        paddingHorizontal: 30,
        width: 340,
        borderRadius: 40,
    },
    botaoOcultar: {
        position: "absolute",
        top: 120,
        right: -12,
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        padding: 4,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 2,
        zIndex: 2,
    },
});
